import type { UserConfig } from "../common/config/userConfig.js";
import { packageInfo } from "../common/packageInfo.js";
import { Server, type ServerOptions } from "../server.js";
import { Session, type SessionOptions } from "../common/session.js";
import { Telemetry } from "../telemetry/telemetry.js";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { LoggerBase } from "../common/logging/index.js";
import { CompositeLogger, ConsoleLogger, DiskLogger, McpLogger } from "../common/logging/index.js";
import { ExportsManager } from "../common/exportsManager.js";
import { DeviceId } from "../helpers/deviceId.js";
import { Keychain } from "../common/keychain.js";
import { defaultCreateConnectionManager } from "../common/connectionManager.js";
import { connectionErrorHandler as defaultConnectionErrorHandler } from "../common/connectionErrorHandler.js";
import type { CommonProperties } from "../telemetry/types.js";
import { Elicitation } from "../elicitation.js";
import { defaultCreateAtlasLocalClient } from "../common/atlasLocal.js";
import { ApiClient } from "../common/atlas/apiClient.js";
import type { UIRegistry } from "../ui/registry/index.js";
import { createDefaultMetrics, PrometheusMetrics, type DefaultMetrics } from "../common/metrics/index.js";
import type { Metrics } from "../common/metrics/metricsTypes.js";

/**
 * Request context containing HTTP headers and query parameters.
 * This type is primarily used by HTTP-based transports.
 */
export type RequestContext = {
    headers?: Record<string, string | string[] | undefined>;
    query?: Record<string, string | string[] | undefined>;
};

export type CustomizableSessionOptions<TUserConfig extends UserConfig = UserConfig> = Partial<
    Pick<
        SessionOptions<TUserConfig>,
        "userConfig" | "apiClient" | "atlasLocalClient" | "connectionManager" | "connectionErrorHandler"
    >
>;

export type CustomizableServerOptions<TUserConfig extends UserConfig = UserConfig, TContext = unknown> = Partial<
    Pick<ServerOptions<TUserConfig, TContext>, "uiRegistry" | "tools" | "toolContext" | "elicitation">
> & {
    /**
     * An optional key value pair of telemetry properties that are reported to
     * the telemetry backend. Most, if not all, of the properties are captured
     * automatically.
     */
    telemetryProperties?: Partial<CommonProperties>;
};

/**
 * Configuration options for customizing how transport runners are initialized.
 * This includes specifying the base user configuration, providing custom
 * connection management, and other advanced options.
 *
 * You may want to customize this configuration if you need to:
 * - Provide a custom user configuration for different environments or users.
 * - Override the default connection management to MongoDB deployments.
 * - Provide a specific list of tools to be registered with the MCP server.
 *
 * In most cases, just providing the `UserConfig` object is sufficient, but
 * advanced use-cases (such as embedding the MCP server in another application
 * or supporting custom authentication flows) may require customizing other
 * `TransportRunnerConfig` options as well.
 *
 * @template TContext - The type of the custom tool context object
 */
export type TransportRunnerConfig<
    TUserConfig extends UserConfig = UserConfig,
    TMetrics extends DefaultMetrics = DefaultMetrics,
> = {
    /**
     * Base user configuration for the server.
     *
     * Can be generated by parsing CLI arguments, environment variables or
     * written manually while conforming the interface requirements of
     * `UserConfig`.
     *
     * To parse CLI arguments and environment variables in order to generate a
     * `UserConfig` object, you can use `parseUserConfig` function, also
     * exported as `parseUserConfig` through MCP server library
     * exports.
     *
     * Optionally, you can also use `UserConfigSchema` (available through MCP
     * server library exports) to create a default configuration -
     * `UserConfigSchema.parse({})`.
     */
    userConfig: TUserConfig;

    /**
     * An optional list of loggers to be used in addition to the default logger
     * implementations. When not provided, MongoDB MCP Server will not utilize
     * any loggers other than the default that it works with.
     *
     * Customize this only if the default enabled loggers (disk/stderr/mcp) are
     * not covering your use-case.
     */
    additionalLoggers?: LoggerBase[];

    /**
     * An optional `Metrics` instance to use for recording metrics. When not
     * provided, MongoDB MCP Server creates an internal `PrometheusMetrics`
     * instance that tracks the built-in default metrics.
     *
     * Pass a custom instance when you need to:
     * - Add application-specific metrics alongside the built-in ones (e.g. for
     *   use by custom tools).
     * - Control the underlying Prometheus `Registry` (e.g. to share it with
     *   other parts of your application).
     *
     * The instance must expose every metric in `DefaultMetrics` so that the
     * built-in tools continue to work correctly.  The recommended way to
     * construct the value is:
     *
     * ```ts
     * import { PrometheusMetrics, createDefaultMetrics } from "mongodb-mcp-server";
     * import { Counter } from "prom-client";
     *
     * const metrics = new PrometheusMetrics({
     *     definitions: {
     *         ...createDefaultMetrics(),
     *         myCounter: new Counter({ name: "my_counter", help: "...", registers: [] }),
     *     },
     * });
     * ```
     */
    metrics?: Metrics<TMetrics>;
};

export abstract class TransportRunnerBase<
    TUserConfig extends UserConfig = UserConfig,
    TContext = unknown,
    TMetrics extends DefaultMetrics = DefaultMetrics,
> {
    public logger: LoggerBase;
    public metrics: Metrics<TMetrics>;

    public deviceId: DeviceId;
    /** Base user configuration for the server. */
    protected readonly userConfig: TUserConfig;

    protected constructor({
        userConfig,
        additionalLoggers = [],
        metrics,
    }: TransportRunnerConfig<TUserConfig, TMetrics>) {
        this.userConfig = userConfig;
        this.metrics = metrics ?? new PrometheusMetrics({ definitions: createDefaultMetrics() as TMetrics });
        const loggers: LoggerBase[] = [...additionalLoggers];
        if (this.userConfig.loggers.includes("stderr")) {
            loggers.push(new ConsoleLogger(Keychain.root));
        }

        if (this.userConfig.loggers.includes("disk")) {
            loggers.push(
                new DiskLogger(
                    this.userConfig.logPath,
                    (err) => {
                        // If the disk logger fails to initialize, we log the error to stderr and exit
                        // eslint-disable-next-line no-console
                        console.error("Error initializing disk logger:", err);
                        process.exit(1);
                    },
                    Keychain.root
                )
            );
        }

        this.logger = new CompositeLogger(...loggers);
        this.deviceId = DeviceId.create(this.logger);
    }

    /**
     * Creates a new MCP server instance with the provided configuration.
     * This method handles server instantiation but does NOT perform session config resolution.
     *
     * @param config - Configuration object containing userConfig and optional serverOptions
     * @returns A configured Server instance
     */
    protected async createServer({
        userConfig = this.userConfig,
        serverOptions,
        sessionOptions,
        logger = new CompositeLogger(this.logger),
    }: {
        userConfig?: TUserConfig;
        logger?: CompositeLogger;
        serverOptions?: CustomizableServerOptions<TUserConfig, TContext>;
        sessionOptions?: CustomizableSessionOptions<TUserConfig>;
    } = {}): Promise<Server<TUserConfig, TContext>> {
        const mcpServer = new McpServer(
            {
                name: packageInfo.mcpServerName,
                version: packageInfo.version,
            },
            {
                instructions: TransportRunnerBase.getInstructions(userConfig),
            }
        );

        const exportsManager = ExportsManager.init(userConfig, logger);

        const connectionManager =
            sessionOptions?.connectionManager ??
            (await defaultCreateConnectionManager({ logger: logger, deviceId: this.deviceId, userConfig }));

        const apiClient =
            userConfig.apiClientId && userConfig.apiClientSecret
                ? new ApiClient(
                      {
                          baseUrl: userConfig.apiBaseUrl,
                          credentials: {
                              clientId: userConfig.apiClientId,
                              clientSecret: userConfig.apiClientSecret,
                          },
                      },
                      logger
                  )
                : undefined;

        const session = new Session({
            userConfig,
            atlasLocalClient:
                sessionOptions?.atlasLocalClient ?? (await defaultCreateAtlasLocalClient({ logger: this.logger })),
            logger,
            connectionErrorHandler: sessionOptions?.connectionErrorHandler ?? defaultConnectionErrorHandler,
            exportsManager,
            connectionManager,
            keychain: Keychain.root,
            apiClient: sessionOptions?.apiClient ?? apiClient,
        });

        const telemetry = Telemetry.create(session, userConfig, this.deviceId, {
            commonProperties: serverOptions?.telemetryProperties,
        });

        let uiRegistry: UIRegistry | undefined = serverOptions?.uiRegistry;
        if (!uiRegistry && userConfig.previewFeatures.includes("mcpUI")) {
            const uiRegistryModule = await import("../ui/registry/registry.js");
            uiRegistry = new uiRegistryModule.UIRegistry();
        }

        const result = new Server<TUserConfig, TContext>({
            mcpServer,
            session,
            telemetry,
            userConfig,
            elicitation: serverOptions?.elicitation ?? new Elicitation({ server: mcpServer.server }),
            tools: serverOptions?.tools,
            uiRegistry,
            toolContext: serverOptions?.toolContext,
            metrics: this.metrics,
        });

        // We need to create the MCP logger after the server is constructed
        // because it needs the server instance
        if (userConfig.loggers.includes("mcp")) {
            logger.addLogger(new McpLogger(result, Keychain.root));
        }

        return result;
    }

    abstract start({
        serverOptions,
        sessionOptions,
    }: {
        /** Upstream `serverOptions` passed from running `runner.start({ serverOptions })` method */
        serverOptions?: ServerOptions<TUserConfig, TContext>;
        /** Upstream `sessionOptions` passed from running `runner.start({ sessionOptions })` method */
        sessionOptions?: SessionOptions<TUserConfig>;
    }): Promise<void>;

    abstract closeTransport(): Promise<void>;

    async close(): Promise<void> {
        try {
            await this.closeTransport();
        } finally {
            this.deviceId.close();
        }
    }

    protected static getInstructions(config: UserConfig): string {
        let instructions = `
            This is the MongoDB MCP server.
        `;
        if (config.connectionString) {
            instructions += `
            This MCP server was configured with a MongoDB connection string, and you can assume that you are connected to a MongoDB cluster.
            `;
        }

        if (config.apiClientId && config.apiClientSecret) {
            instructions += `
            This MCP server was configured with MongoDB Atlas API credentials.`;
        }

        return instructions;
    }
}
