import type { UserConfig } from "../common/config/userConfig.js";
import { packageInfo } from "../common/packageInfo.js";
import { Server, type ServerOptions } from "../server.js";
import { Session } from "../common/session.js";
import { Telemetry } from "../telemetry/telemetry.js";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { LoggerBase } from "../common/logging/index.js";
import { CompositeLogger, ConsoleLogger, DiskLogger, McpLogger } from "../common/logging/index.js";
import { ExportsManager } from "../common/exportsManager.js";
import { DeviceId } from "../helpers/deviceId.js";
import { Keychain } from "../common/keychain.js";
import { DIContainer } from "../common/diContainer.js";
import type { ConnectionManager } from "../common/connectionManager.js";
import { MCPConnectionManager } from "../common/connectionManager.js";
import {
    connectionErrorHandler as defaultConnectionErrorHandler,
    type ConnectionErrorHandler,
} from "../common/connectionErrorHandler.js";
import type { Client } from "@mongodb-js/atlas-local";
import type { CommonProperties } from "../telemetry/types.js";
import { Elicitation } from "../elicitation.js";
import { defaultCreateAtlasLocalClient } from "../common/atlasLocal.js";
import { ApiClient } from "../common/atlas/apiClient.js";
import type { UIRegistry } from "../ui/registry/index.js";
import { createDefaultMetrics, PrometheusMetrics, type DefaultMetrics } from "../common/metrics/index.js";
import type { Metrics } from "../common/metrics/metricsTypes.js";

/**
 * Request context containing HTTP headers and query parameters.
 * This type is primarily used by HTTP-based transports.
 */
export type RequestContext = {
    headers?: Record<string, string | string[] | undefined>;
    query?: Record<string, string | string[] | undefined>;
};

export type CustomizableServerOptions<TUserConfig extends UserConfig = UserConfig, TContext = unknown> = Partial<
    Pick<ServerOptions<TUserConfig, TContext>, "uiRegistry" | "tools" | "toolContext" | "elicitation">
> & {
    /**
     * An optional key value pair of telemetry properties that are reported to
     * the telemetry backend. Most, if not all, of the properties are captured
     * automatically.
     */
    telemetryProperties?: Partial<CommonProperties>;
};

/**
 * Shape of the runner-scoped DI container.
 */
export type RunnerCradle = {
    userConfig: UserConfig;
    keychain: Keychain;
    loggers: LoggerBase[];
    logger: CompositeLogger;
    deviceId: DeviceId;
};

/**
 * Shape of the server-scoped DI container passed to `createServer`.
 * Server-scoped containers are typically created via `runner.createServerContainer()`,
 * which scopes from the runner container so factories can inject runner-level
 * dependencies (`userConfig`, `keychain`, etc.).
 */
export type ServerCradle = {
    logger: CompositeLogger;
    connectionManager: ConnectionManager;
    atlasLocalClient?: Client;
    apiClient?: ApiClient;
    connectionErrorHandler: ConnectionErrorHandler;
    exportsManager: ExportsManager;
    session: Session;
};

/**
 * Configuration options for customizing how transport runners are initialized.
 * This includes specifying the base user configuration, providing custom
 * connection management, and other advanced options.
 *
 * You may want to customize this configuration if you need to:
 * - Provide a custom user configuration for different environments or users.
 * - Override the default connection management to MongoDB deployments.
 * - Provide a specific list of tools to be registered with the MCP server.
 *
 * In most cases, just providing the `UserConfig` object is sufficient, but
 * advanced use-cases (such as embedding the MCP server in another application
 * or supporting custom authentication flows) may require customizing other
 * `TransportRunnerConfig` options as well.
 *
 * @template TContext - The type of the custom tool context object
 */
export type TransportRunnerConfig<
    TUserConfig extends UserConfig = UserConfig,
    TMetrics extends DefaultMetrics = DefaultMetrics,
> = {
    /**
     * Base user configuration for the server.
     *
     * Can be generated by parsing CLI arguments, environment variables or
     * written manually while conforming the interface requirements of
     * `UserConfig`.
     *
     * To parse CLI arguments and environment variables in order to generate a
     * `UserConfig` object, you can use `parseUserConfig` function, also
     * exported as `parseUserConfig` through MCP server library
     * exports.
     *
     * Optionally, you can also use `UserConfigSchema` (available through MCP
     * server library exports) to create a default configuration -
     * `UserConfigSchema.parse({})`.
     */
    userConfig: TUserConfig;

    /**
     * An optional callback invoked before the runner builds its composite logger.
     * Use this to register additional logger implementations or other dependencies.
     *
     * Logger implementations are registered via `container.register`, e.g.:
     * `container.register("loggers", "cloud", container.asFunction(({ userConfig, keychain }) => new MyCloudLogger(userConfig.apiKey, keychain)).singleton())`.
     * All `loggers` registrations are collected automatically into the composite logger.
     * Both `userConfig` and `keychain` are available in the cradle for factory functions.
     */
    configureDependencies?: (container: DIContainer<RunnerCradle>) => void;

    /**
     * An optional `Metrics` instance to use for recording metrics. When not
     * provided, MongoDB MCP Server creates an internal `PrometheusMetrics`
     * instance that tracks the built-in default metrics.
     *
     * Pass a custom instance when you need to:
     * - Add application-specific metrics alongside the built-in ones (e.g. for
     *   use by custom tools).
     * - Control the underlying Prometheus `Registry` (e.g. to share it with
     *   other parts of your application).
     *
     * The instance must expose every metric in `DefaultMetrics` so that the
     * built-in tools continue to work correctly.  The recommended way to
     * construct the value is:
     *
     * ```ts
     * import { PrometheusMetrics, createDefaultMetrics } from "mongodb-mcp-server";
     * import { Counter } from "prom-client";
     *
     * const metrics = new PrometheusMetrics({
     *     definitions: {
     *         ...createDefaultMetrics(),
     *         myCounter: new Counter({ name: "my_counter", help: "...", registers: [] }),
     *     },
     * });
     * ```
     */
    metrics?: Metrics<TMetrics>;
};

export abstract class TransportRunnerBase<
    TUserConfig extends UserConfig = UserConfig,
    TContext = unknown,
    TMetrics extends DefaultMetrics = DefaultMetrics,
> {
    public logger: LoggerBase;
    public metrics: Metrics<TMetrics>;

    /** Base user configuration for the server. */
    protected readonly userConfig: TUserConfig;
    /** Runner-scoped DI container. Use `runnerContainer.createScope<ServerCradle>()` to create a server-scoped child. */
    public readonly runnerContainer: DIContainer<RunnerCradle>;

    protected constructor({
        userConfig,
        configureDependencies,
        metrics,
    }: TransportRunnerConfig<TUserConfig, TMetrics>) {
        this.userConfig = userConfig;
        this.metrics = metrics ?? new PrometheusMetrics({ definitions: createDefaultMetrics() as TMetrics });

        this.runnerContainer = new DIContainer<RunnerCradle>();

        this.runnerContainer.register("userConfig", this.runnerContainer.asValue(userConfig));
        this.runnerContainer.register("keychain", this.runnerContainer.asValue(Keychain.root));

        configureDependencies?.(this.runnerContainer);

        if (userConfig.loggers.includes("stderr")) {
            this.runnerContainer.register(
                "loggers",
                "console",
                this.runnerContainer.asFunction(({ keychain }) => new ConsoleLogger(keychain)).singleton()
            );
        }

        if (userConfig.loggers.includes("disk")) {
            this.runnerContainer.register(
                "loggers",
                "disk",
                this.runnerContainer
                    .asFunction(
                        ({ userConfig, keychain }) =>
                            new DiskLogger(
                                userConfig.logPath,
                                (err) => {
                                    // eslint-disable-next-line no-console
                                    console.error("Error initializing disk logger:", err);
                                    process.exit(1);
                                },
                                keychain
                            )
                    )
                    .singleton()
            );
        }

        // resolve("loggers") throws if nothing was registered (e.g. loggers: [] with no
        // configureDependencies). Guard so an empty config produces a silent composite logger.
        let loggers: LoggerBase[];
        try {
            loggers = this.runnerContainer.resolve("loggers");
        } catch {
            loggers = [];
        }
        const logger = new CompositeLogger(...loggers);
        this.runnerContainer.register("logger", this.runnerContainer.asValue(logger));

        this.runnerContainer.register(
            "deviceId",
            this.runnerContainer
                .asFunction(({ logger }) => DeviceId.create(logger))
                .singleton()
                .disposer((deviceId) => deviceId.close())
        );

        this.logger = logger;
    }

    /**
     * Creates a fully-populated server-scoped DI container by scoping from the runner
     * container and registering defaults for all `ServerCradle` dependencies.
     *
     * Pass a `userConfig` override to shadow the runner-level config on the scope —
     * useful for per-request config overrides in HTTP transports.
     *
     * Callers can override individual dependencies by registering them on the returned
     * container before passing it to `createServer`.
     */
    protected async createServerContainer(userConfig?: TUserConfig): Promise<DIContainer<RunnerCradle & ServerCradle>> {
        const c = this.runnerContainer.createScope<ServerCradle>();

        if (userConfig !== undefined) {
            c.register("userConfig", c.asValue(userConfig));
        }

        c.register("logger", c.asValue(new CompositeLogger(this.logger)));

        c.register(
            "connectionManager",
            c
                .asFunction(
                    ({ userConfig, logger, deviceId }) => new MCPConnectionManager(userConfig, logger, deviceId)
                )
                .scoped()
        );

        const logger = c.resolve("logger");
        c.register("atlasLocalClient", c.asValue(await defaultCreateAtlasLocalClient({ logger })));

        c.register(
            "apiClient",
            c
                .asFunction(({ userConfig, logger }) =>
                    userConfig.apiClientId && userConfig.apiClientSecret
                        ? new ApiClient(
                              {
                                  baseUrl: userConfig.apiBaseUrl,
                                  credentials: {
                                      clientId: userConfig.apiClientId,
                                      clientSecret: userConfig.apiClientSecret,
                                  },
                              },
                              logger
                          )
                        : undefined
                )
                .scoped()
        );

        c.register("connectionErrorHandler", c.asValue(defaultConnectionErrorHandler));

        c.register(
            "exportsManager",
            c.asFunction(({ userConfig, logger }) => ExportsManager.init(userConfig, logger)).scoped()
        );

        c.register("session", c.asClass(Session).scoped());

        return c;
    }

    /**
     * Creates a new MCP server instance with the provided configuration.
     * Dependencies are resolved from the `container`, which should be created via
     * `createServerContainer()` and optionally customised before being passed in.
     *
     * @returns A configured Server instance
     */
    protected async createServer({
        userConfig = this.userConfig,
        container,
        serverOptions,
    }: {
        userConfig?: TUserConfig;
        container?: DIContainer<ServerCradle>;
        serverOptions?: CustomizableServerOptions<TUserConfig, TContext>;
    } = {}): Promise<Server<TUserConfig, TContext>> {
        container ??= await this.createServerContainer(userConfig);
        const logger = container.resolve("logger");
        const session = container.resolve("session");

        const mcpServer = new McpServer(
            {
                name: packageInfo.mcpServerName,
                version: packageInfo.version,
            },
            {
                instructions: TransportRunnerBase.getInstructions(userConfig),
            }
        );

        const telemetry = Telemetry.create(session, userConfig, this.runnerContainer.resolve("deviceId"), {
            commonProperties: serverOptions?.telemetryProperties,
        });

        let uiRegistry: UIRegistry | undefined = serverOptions?.uiRegistry;
        if (!uiRegistry && userConfig.previewFeatures.includes("mcpUI")) {
            const uiRegistryModule = await import("../ui/registry/registry.js");
            uiRegistry = new uiRegistryModule.UIRegistry();
        }

        const result = new Server<TUserConfig, TContext>({
            mcpServer,
            session,
            telemetry,
            userConfig,
            elicitation: serverOptions?.elicitation ?? new Elicitation({ server: mcpServer.server }),
            tools: serverOptions?.tools,
            uiRegistry,
            toolContext: serverOptions?.toolContext,
            metrics: this.metrics,
        });

        // We need to create the MCP logger after the server is constructed
        // because it needs the server instance
        if (userConfig.loggers.includes("mcp")) {
            logger.addLogger(new McpLogger(result, Keychain.root));
        }

        return result;
    }

    abstract start({ serverOptions }: { serverOptions?: ServerOptions<TUserConfig, TContext> }): Promise<void>;

    abstract closeTransport(): Promise<void>;

    async close(): Promise<void> {
        try {
            await this.closeTransport();
        } finally {
            await this.runnerContainer.dispose();
        }
    }

    protected static getInstructions(config: UserConfig): string {
        let instructions = `
            This is the MongoDB MCP server.
        `;
        if (config.connectionString) {
            instructions += `
            This MCP server was configured with a MongoDB connection string, and you can assume that you are connected to a MongoDB cluster.
            `;
        }

        if (config.apiClientId && config.apiClientSecret) {
            instructions += `
            This MCP server was configured with MongoDB Atlas API credentials.`;
        }

        return instructions;
    }
}
